services:

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_APP_PORT}:8501"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8501/_stcore/health"
        ]
    volumes:
      - ./.streamlit:/app/.streamlit
      - ./grobid:/app/grobid
      - config.json:/app/config.json
    entrypoint:
      [
        "streamlit",
        "run",
        "streamlit_app.py",
        "--server.port=8501",
        "--server.address=0.0.0.0"
      ]
    depends_on:
      - grobid

  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "${GROBID_PORT}:8070"
    ulimits:
      core:
        soft: 0
        hard: 0
    init: true
    restart: always
